import type { StockBalance } from '@wms/domain'

export const WAREHOUSES_MOCK = [
  { id: 'wh-1', name: 'Главный склад', type: 'main' as const, items: 8, halfEmpty: 1, disposal: 1 },
  { id: 'wh-field-1', name: 'Дочерний склад №1', type: 'child' as const, items: 6, halfEmpty: 1, disposal: 1 },
  { id: 'wh-field-2', name: 'Дочерний склад №2', type: 'child' as const, items: 6, halfEmpty: 1, disposal: 1 },
]

export const DEMO_STOCK: StockBalance[] = [
  {
    warehouseId: 'wh-1',
    productName: 'Тестовый СЗР 1 - гербицид',
    unit: 'л',
    quantity: 4800,
    expiryDate: '2027-05-10',
    status: 'on_warehouse',
    batchNumber: 'B-2401',
    cost: 4320000,
  },
  {
    warehouseId: 'wh-1',
    productName: 'Тестовый СЗР 2 - фунгицид',
    unit: 'л',
    quantity: 2360,
    expiryDate: '2027-03-18',
    status: 'on_warehouse',
    batchNumber: 'B-2398',
    cost: 2596000,
  },
  {
    warehouseId: 'wh-1',
    productName: 'Тестовый СЗР 3 - инсектицид',
    unit: 'л',
    quantity: 1240,
    expiryDate: '2026-11-22',
    status: 'on_warehouse',
    batchNumber: 'B-2391',
    cost: 1488000,
  },
  {
    warehouseId: 'wh-1',
    productName: 'Тестовое удобрение 1 - комплексное',
    unit: 'кг',
    quantity: 8600,
    expiryDate: '2028-08-04',
    status: 'on_warehouse',
    batchNumber: 'F-2405',
    cost: 3010000,
  },
  {
    warehouseId: 'wh-1',
    productName: 'Тестовая тара СЗР - полупустая',
    unit: 'л',
    quantity: 420,
    expiryDate: '2026-09-15',
    status: 'half_empty',
    batchNumber: 'R-2380',
    cost: 378000,
  },
  {
    warehouseId: 'wh-1',
    productName: 'Тестовая тара СЗР - на утилизацию',
    unit: 'шт',
    quantity: 310,
    expiryDate: '2027-01-30',
    status: 'disposal',
    batchNumber: 'U-2395',
    cost: 0,
  },
  {
    warehouseId: 'wh-1',
    productName: 'Тестовые семена 1 - яровая пшеница',
    unit: 'кг',
    quantity: 24000,
    expiryDate: '2028-04-01',
    status: 'on_warehouse',
    batchNumber: 'S-1102',
    cost: 5760000,
  },
  {
    warehouseId: 'wh-1',
    productName: 'Тестовый СЗР 4 - протравитель',
    unit: 'л',
    quantity: 920,
    expiryDate: '2027-12-12',
    status: 'on_warehouse',
    batchNumber: 'T-2412',
    cost: 1196000,
  },
  {
    warehouseId: 'wh-field-1',
    productName: 'Тестовый СЗР 1 - гербицид',
    unit: 'л',
    quantity: 640,
    expiryDate: '2027-05-10',
    status: 'on_warehouse',
    batchNumber: 'B-2401',
    cost: 576000,
  },
  {
    warehouseId: 'wh-field-1',
    productName: 'Тестовый СЗР 2 - фунгицид',
    unit: 'л',
    quantity: 280,
    expiryDate: '2027-03-18',
    status: 'on_warehouse',
    batchNumber: 'B-2398',
    cost: 308000,
  },
  {
    warehouseId: 'wh-field-1',
    productName: 'Тестовый СЗР 3 - инсектицид',
    unit: 'л',
    quantity: 190,
    expiryDate: '2026-11-22',
    status: 'on_warehouse',
    batchNumber: 'B-2391',
    cost: 228000,
  },
  {
    warehouseId: 'wh-field-1',
    productName: 'Тестовое удобрение 1 - комплексное',
    unit: 'кг',
    quantity: 1300,
    expiryDate: '2028-08-04',
    status: 'on_warehouse',
    batchNumber: 'F-2405',
    cost: 455000,
  },
  {
    warehouseId: 'wh-field-1',
    productName: 'Тестовая тара СЗР - полупустая',
    unit: 'л',
    quantity: 75,
    expiryDate: '2026-09-15',
    status: 'half_empty',
    batchNumber: 'R-2380',
    cost: 67500,
  },
  {
    warehouseId: 'wh-field-1',
    productName: 'Тестовая тара СЗР - на утилизацию',
    unit: 'шт',
    quantity: 46,
    expiryDate: '2027-01-30',
    status: 'disposal',
    batchNumber: 'U-2395',
    cost: 0,
  },
  {
    warehouseId: 'wh-field-2',
    productName: 'Тестовый СЗР 1 - гербицид',
    unit: 'л',
    quantity: 520,
    expiryDate: '2027-05-10',
    status: 'on_warehouse',
    batchNumber: 'B-2401',
    cost: 468000,
  },
  {
    warehouseId: 'wh-field-2',
    productName: 'Тестовый СЗР 2 - фунгицид',
    unit: 'л',
    quantity: 430,
    expiryDate: '2027-03-18',
    status: 'on_warehouse',
    batchNumber: 'B-2398',
    cost: 473000,
  },
  {
    warehouseId: 'wh-field-2',
    productName: 'Тестовый СЗР 4 - протравитель',
    unit: 'л',
    quantity: 150,
    expiryDate: '2027-12-12',
    status: 'on_warehouse',
    batchNumber: 'T-2412',
    cost: 195000,
  },
  {
    warehouseId: 'wh-field-2',
    productName: 'Тестовые семена 1 - яровая пшеница',
    unit: 'кг',
    quantity: 4100,
    expiryDate: '2028-04-01',
    status: 'on_warehouse',
    batchNumber: 'S-1102',
    cost: 984000,
  },
  {
    warehouseId: 'wh-field-2',
    productName: 'Тестовая тара СЗР - полупустая',
    unit: 'л',
    quantity: 54,
    expiryDate: '2026-09-15',
    status: 'half_empty',
    batchNumber: 'R-2380',
    cost: 48600,
  },
  {
    warehouseId: 'wh-field-2',
    productName: 'Тестовая тара СЗР - на утилизацию',
    unit: 'шт',
    quantity: 32,
    expiryDate: '2027-01-30',
    status: 'disposal',
    batchNumber: 'U-2395',
    cost: 0,
  },
]

export const INITIAL_STOCK: StockBalance[] = DEMO_STOCK

export const WAREHOUSE_VIEW_TABS = ['balances', 'operations', 'inventory', 'receipt'] as const

export type WarehouseViewTab = (typeof WAREHOUSE_VIEW_TABS)[number]

export const WAREHOUSE_VIEW_TAB_LABELS: Record<WarehouseViewTab, string> = {
  balances: 'Остатки',
  operations: 'Операции',
  inventory: 'Инвентаризация',
  receipt: 'Приёмка',
}
