import type { WarehouseTask } from '@wms/domain'

export const DEMO_WAREHOUSE_TASKS: WarehouseTask[] = [
  {
    id: 'wt-demo-001',
    number: 'WH-2026-001',
    operationType: 'receiving',
    status: 'ready',
    priority: 'high',
    sourceType: 'auto',
    sourceDocumentId: 'er-demo-001',
    sourceDocumentType: 'supplier_document',
    sourceLabel: 'Ожидаемая приемка ОП-001 · тестовый файл поставщика',
    createdByName: 'Система',
    assignedByType: 'system',
    assignedByName: 'Система',
    assignedToType: 'group',
    assignedToName: 'Кладовщики ГС',
    fromLocationName: 'Поставщик',
    toLocationName: 'Главный склад',
    expectedQty: 420,
    scannedQty: 0,
    acceptedQty: 0,
    comment: 'Тестовая приемка: 2 палеты / 42 коробки / 420 канистр',
    createdAt: '2026-10-01T08:15:00.000Z',
    history: [
      { id: 'h-001-1', at: '2026-10-01T08:15:00.000Z', text: 'Создана автоматически из ожидаемой приемки' },
      { id: 'h-001-2', at: '2026-10-01T08:17:00.000Z', text: 'Назначена группе: Кладовщики ГС' },
    ],
  },
  {
    id: 'wt-demo-002',
    number: 'WH-2026-002',
    operationType: 'transfer',
    status: 'in_progress',
    priority: 'high',
    sourceType: 'auto',
    sourceDocumentId: 'req-demo-001',
    sourceDocumentType: 'request',
    sourceLabel: 'Заявка дочернего склада №1',
    createdByName: 'Система',
    assignedByType: 'system',
    assignedByName: 'Система',
    assignedToType: 'group',
    assignedToName: 'Кладовщики ГС',
    actualExecutorName: 'Ерлан Садыков',
    actualExecutorStartedAt: '2026-10-01T08:40:00.000Z',
    fromLocationName: 'Главный склад',
    toLocationName: 'Дочерний склад №1',
    expectedQty: 120,
    scannedQty: 64,
    acceptedQty: 64,
    comment: 'Отгрузка СЗР по заявке дочернего склада №1',
    linkedTaskId: 'wt-demo-003',
    handshakeRole: 'sender',
    createdAt: '2026-10-01T08:30:00.000Z',
    startedAt: '2026-10-01T08:40:00.000Z',
    history: [
      { id: 'h-002-1', at: '2026-10-01T08:30:00.000Z', text: 'Создана задача отправителя по перемещению' },
      { id: 'h-002-2', at: '2026-10-01T08:40:00.000Z', text: 'Исполнитель взял задачу в работу на ТСД' },
      { id: 'h-002-3', at: '2026-10-01T08:54:00.000Z', text: 'Отсканировано 64 из 120 канистр' },
    ],
  },
  {
    id: 'wt-demo-003',
    number: 'WH-2026-003',
    operationType: 'transfer',
    status: 'awaiting_receiver_confirmation',
    priority: 'high',
    sourceType: 'auto',
    sourceDocumentId: 'tr-demo-001',
    sourceDocumentType: 'transfer',
    sourceLabel: 'Прием перемещения с главного склада',
    createdByName: 'Система',
    assignedByType: 'system',
    assignedByName: 'Система',
    assignedToType: 'group',
    assignedToName: 'Кладовщики ДС №1',
    fromLocationName: 'Главный склад',
    toLocationName: 'Дочерний склад №1',
    expectedQty: 120,
    scannedQty: 0,
    acceptedQty: 0,
    comment: 'Ожидает второго подтверждения со стороны дочернего склада',
    linkedTaskId: 'wt-demo-002',
    handshakeRole: 'receiver',
    createdAt: '2026-10-01T08:31:00.000Z',
    history: [
      { id: 'h-003-1', at: '2026-10-01T08:31:00.000Z', text: 'Создана парная задача приемки перемещения' },
      { id: 'h-003-2', at: '2026-10-01T08:56:00.000Z', text: 'Ожидает подтверждения после отгрузки отправителем' },
    ],
  },
  {
    id: 'wt-demo-004',
    number: 'WH-2026-004',
    operationType: 'issue',
    status: 'completed',
    priority: 'normal',
    sourceType: 'manual',
    sourceDocumentId: 'act-issue-demo-001',
    sourceDocumentType: 'act',
    sourceLabel: 'Акт выдачи агроному АВ-001',
    createdByName: 'Кладовщик ДС №1',
    assignedByType: 'user',
    assignedByName: 'Кладовщик ДС №1',
    assignedToType: 'user',
    assignedToName: 'Агроном Ермек',
    actualExecutorName: 'Кладовщик ДС №1',
    fromLocationName: 'Дочерний склад №1',
    toLocationName: 'Агроном Ермек',
    expectedQty: 36,
    scannedQty: 36,
    acceptedQty: 36,
    comment: 'Выдача на поле №4, тестовый акт сформирован',
    createdAt: '2026-09-30T12:10:00.000Z',
    startedAt: '2026-09-30T12:14:00.000Z',
    completedAt: '2026-09-30T12:28:00.000Z',
    history: [
      { id: 'h-004-1', at: '2026-09-30T12:10:00.000Z', text: 'Операция создана вручную на ТСД' },
      { id: 'h-004-2', at: '2026-09-30T12:28:00.000Z', text: 'Выдача подтверждена, акт сформирован' },
    ],
  },
  {
    id: 'wt-demo-005',
    number: 'WH-2026-005',
    operationType: 'return',
    status: 'discrepancy',
    priority: 'urgent',
    sourceType: 'manual',
    sourceDocumentId: 'ret-demo-001',
    sourceDocumentType: 'return',
    sourceLabel: 'Возврат тары от агронома',
    createdByName: 'Агроном Ермек',
    assignedByType: 'user',
    assignedByName: 'Агроном Ермек',
    assignedToType: 'group',
    assignedToName: 'Кладовщики ДС №1',
    actualExecutorName: 'Кладовщик ДС №1',
    fromLocationName: 'Агроном Ермек',
    toLocationName: 'Дочерний склад №1',
    expectedQty: 36,
    scannedQty: 34,
    acceptedQty: 34,
    discrepancyReason: '2 канистры не вернулись, 4 полупустые требуют фотофиксации',
    comment: 'Тестовое расхождение по возврату с поля',
    createdAt: '2026-09-30T16:45:00.000Z',
    startedAt: '2026-09-30T16:50:00.000Z',
    history: [
      { id: 'h-005-1', at: '2026-09-30T16:45:00.000Z', text: 'Создан возврат от агронома' },
      { id: 'h-005-2', at: '2026-09-30T16:55:00.000Z', text: 'Зафиксировано расхождение: не хватает 2 канистр' },
      { id: 'h-005-3', at: '2026-09-30T16:58:00.000Z', text: 'Добавлена фотофиксация полупустой тары' },
    ],
  },
  {
    id: 'wt-demo-006',
    number: 'WH-2026-006',
    operationType: 'utilization',
    status: 'ready',
    priority: 'normal',
    sourceType: 'auto',
    sourceDocumentId: 'util-demo-001',
    sourceDocumentType: 'act',
    sourceLabel: 'Партия пустой тары на утилизацию',
    createdByName: 'Система',
    assignedByType: 'system',
    assignedByName: 'Система',
    assignedToType: 'group',
    assignedToName: 'Кладовщики ГС',
    fromLocationName: 'Главный склад',
    toLocationName: 'Зона утилизации',
    expectedQty: 310,
    scannedQty: 0,
    acceptedQty: 0,
    comment: 'Проверить партию тары перед передачей на утилизацию',
    createdAt: '2026-10-01T07:20:00.000Z',
    history: [
      { id: 'h-006-1', at: '2026-10-01T07:20:00.000Z', text: 'Создана задача утилизации по накопленной таре' },
    ],
  },
  {
    id: 'wt-demo-007',
    number: 'WH-2026-007',
    operationType: 'inventory',
    status: 'assigned',
    priority: 'normal',
    sourceType: 'manual',
    sourceDocumentId: 'inv-demo-001',
    sourceDocumentType: 'inventory',
    sourceLabel: 'Выборочная инвентаризация зоны B',
    createdByName: 'Администратор склада',
    assignedByType: 'user',
    assignedByName: 'Администратор склада',
    assignedToType: 'group',
    assignedToName: 'Кладовщики ДС №2',
    fromLocationName: 'Дочерний склад №2',
    toLocationName: 'Зона B',
    expectedQty: 6,
    scannedQty: 0,
    acceptedQty: 0,
    comment: 'Проверить остатки СЗР и семян по зоне B',
    createdAt: '2026-10-01T09:10:00.000Z',
    history: [
      { id: 'h-007-1', at: '2026-10-01T09:10:00.000Z', text: 'Инвентаризация создана вручную' },
      { id: 'h-007-2', at: '2026-10-01T09:12:00.000Z', text: 'Назначена группе кладовщиков ДС №2' },
    ],
  },
  {
    id: 'wt-demo-008',
    number: 'WH-2026-008',
    operationType: 'writeoff',
    status: 'cancelled',
    priority: 'low',
    sourceType: 'manual',
    sourceDocumentId: 'wr-demo-001',
    sourceDocumentType: 'act',
    sourceLabel: 'Списание тестовой позиции',
    createdByName: 'Администратор склада',
    assignedByType: 'user',
    assignedByName: 'Администратор склада',
    assignedToType: 'user',
    assignedToName: 'Кладовщик ГС',
    fromLocationName: 'Главный склад',
    toLocationName: 'Списание',
    expectedQty: 12,
    scannedQty: 0,
    acceptedQty: 0,
    cancelReason: 'Операция больше не нужна',
    comment: 'Тестовая отмененная операция для проверки статуса',
    createdAt: '2026-09-29T10:05:00.000Z',
    completedAt: '2026-09-29T10:20:00.000Z',
    history: [
      { id: 'h-008-1', at: '2026-09-29T10:05:00.000Z', text: 'Создана операция списания' },
      { id: 'h-008-2', at: '2026-09-29T10:20:00.000Z', text: 'Операция отменена пользователем' },
    ],
  },
]
